// <auto-generated />
namespace ContactList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changngmodelvaldaton : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changngmodelvaldaton));
        
        string IMigrationMetadata.Id
        {
            get { return "202002062107054_changng model valdaton"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
